version: 2.1
orbs:
  react-native: react-native-community/react-native@1.3.0

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          paths: .
          root: .

  analyse_js:
    executor: rn/linux_js
    steps:
        - attach_workspace:
            at: .
        - rn/yarn_install
        - run:
            command: yarn lint
            name: Run ESLint

  release:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
    - checkout
    - restore_cache:
          name: Restore node modules
          keys:
            - node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
    - run:
          name: Publish to NPM
          command: yarn semantic-release || true

workflows:
  test:
    jobs:
    - checkout_code
    - analyse_js:
        requires:
        - checkout_code
    - release:
        requires:
        - analyse_js
        filters:
            branches:
              only: master
