version: 2
jobs:
  build:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: yarn --pure-lockfile
  test:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
    - checkout
    - run:
        name: Run Linter Check
        command: yarn lint

workflows:
  version: 2
  ci:
    jobs:
    - build
    - test:
        requires:
        - build