version: 2
jobs:
  build:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: yarn --pure-lockfile
  
  test:
  - run:
      name: Lint check
      command: yarn lint

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
        - requires:
          - build